testapp/config/routes.rb
Testapp::Application.routes.draw do
  devise_for :users

  resources :user_configs

  root :to => 'UserConfigs#index'

end

testapp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

testapp/app/models/user_config.rb
class UserConfig < ActiveRecord::Base
  # attr_accessible :title, :body
end

testapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

testapp/app/controllers/user_configs_controller.rb
class UserConfigsController < ApplicationController
  before_filter :authenticate_user!
  # GET /user_configs
  # GET /user_configs.json
  def index
    @user_configs = UserConfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @user_configs }
    end
  end

  # GET /user_configs/1
  # GET /user_configs/1.json
  def show
    @user_config = UserConfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user_config }
    end
  end

  # GET /user_configs/new
  # GET /user_configs/new.json
  def new
    @user_config = UserConfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user_config }
    end
  end

  # GET /user_configs/1/edit
  def edit
    @user_config = UserConfig.find(params[:id])
  end

  # POST /user_configs
  # POST /user_configs.json
  def create
    @user_config = UserConfig.new(params[:user_config])

    respond_to do |format|
      if @user_config.save
        format.html { redirect_to @user_config, :notice => 'User config was successfully created.' }
        format.json { render :json => @user_config, :status => :created, :location => @user_config }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user_config.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_configs/1
  # PUT /user_configs/1.json
  def update
    @user_config = UserConfig.find(params[:id])

    respond_to do |format|
      if @user_config.update_attributes(params[:user_config])
        format.html { redirect_to @user_config, :notice => 'User config was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user_config.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_configs/1
  # DELETE /user_configs/1.json
  def destroy
    @user_config = UserConfig.find(params[:id])
    @user_config.destroy

    respond_to do |format|
      format.html { redirect_to user_configs_url }
      format.json { head :no_content }
    end
  end
end

testapp/app/helpers/application_helper.rb
module ApplicationHelper
end

testapp/app/helpers/user_configs_helper.rb
module UserConfigsHelper
end

testapp/app/views/user_configs/_form.html.erb
<%= form_for(@user_config) do |f| %>
  <% if @user_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_config.errors.count, "error") %> prohibited this user_config from being saved:</h2>

      <ul>
      <% @user_config.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

testapp/app/views/user_configs/edit.html.erb
<h1>Editing user_config</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_config %> |
<%= link_to 'Back', user_configs_path %>

testapp/app/views/user_configs/index.html.erb
<h1>Listing user_configs</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_configs.each do |user_config| %>
  <tr>
    <td><%= link_to 'Show', user_config %></td>
    <td><%= link_to 'Edit', edit_user_config_path(user_config) %></td>
    <td><%= link_to 'Destroy', user_config, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User config', new_user_config_path %>

testapp/app/views/user_configs/new.html.erb
<h1>New user_config</h1>

<%= render 'form' %>

<%= link_to 'Back', user_configs_path %>

testapp/app/views/user_configs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_config_path(@user_config) %> |
<%= link_to 'Back', user_configs_path %>