loungeboard/config/routes.rb
Loungeboard::Application.routes.draw do
  match 'rooms/:name/get_visitors' => 'rooms#get_visitors', :as => :get_visitors
  match 'rooms/update_visitors' => 'rooms#update_visitors', :as => :update_visitors
  resources :rooms do
    put :update_visitors, :on => :member
  end

  resources :bluetooths

  resources :users
  resource :session 
  
  match '/login' => "sessions#new", :as => :login
  match '/logout' => "sessions#destroy", :as => :logout
  
  
  

  
  

  root :to => 'users#index'

end

loungeboard/app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :name
  has_many :bluetooths
  has_many :users,
           :through => :bluetooths
       
end

loungeboard/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, :notice => 'Room was successfully created.' }
        format.json { render :json => @room, :status => :created, :location => @room }
      else
        format.html { render :action => "new" }
        format.json { render :json => @room.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, :notice => 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @room.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
  
  # GET /rooms/:id/get_visitors
  # GET /rooms/:id/get_visitors.xml
  def get_visitors 
    room = Room.find_by_name(params[:name])
    @bluetooths = room.bluetooths.where("updated_at > ?", 5.seconds.ago.to_s)
    
    #For Testing
    #@bluetooths = room.bluetooths.all
    
    @users = []
    @bluetooths.each do |bt|
      @users << bt.user
    end
    
    respond_to do |format|
      format.html # get_visitors.html.erb
      format.json { render :json => @users }
      format.xml { render "get_visitors" }
    end
  end
  
  def update_visitors
    room = Room.find_by_name(params[:name])
    #check if the specified bluetooth is existed
    @bluetooth = Bluetooth.find_by_mac_addr(params[:mac_addr])
    
    if @bluetooth # if bluetooth exist in database
      # Check if the detected bluetooth is already in the room
      if @bluetooth.room_id != room.id # if not in the room, hook it up to the room with room_id = params[:id]
        @bluetooth.room_id = room.id
      end
      @bluetooth.updated_at = Time.now
      @bluetooth.save
    end
     
    respond_to do |format|
      format.html { head :no_content }
      format.json { head :no_content }
      format.xml { head :no_content }
      format.xml { head :no_content }
    end
  end
  
end

loungeboard/app/helpers/rooms_helper.rb
module RoomsHelper
end

loungeboard/app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

loungeboard/app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

loungeboard/app/views/rooms/get_visitors.html.erb
<h1>Visitors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Twitter</th>
  </tr>

<% if @users %>
	<% @users.each do |user| %>
	  <tr>
	    <td><%= user.name %></td>
	    <td><%= user.twitter %></td>
	  </tr>
 	<% end %>
<% end %>
</table>

<br />

loungeboard/app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.name %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>

loungeboard/app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

loungeboard/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @room.name %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

loungeboard/app/views/rooms/update_visitors.html.erb
<h1>Update Visitors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Updated at</th>
  </tr>

  <tr>
  	<% if @bluetooth %>
    <td><%= @bluetooth.user.name %></td>
    <td><%= @bluetooth.updated_at %></td>
    <% end %>
  </tr>
</table>

<br />